### ISSUE TITLE
osu lazer API support?

### ISSUE THREAD

**Issue by diamondburned** [thehowl/go-osuapi#2]
Hello. Is there a planned ETA for osu lazer support? I'm currently working on one, and was wondering if it will go up soon so I could do some merge requests.

**Comment by thehowl** [comment]
Hey there! Sorry about the late reply.

I don't really intend to work on the Lazer API myself, mostly because I don't want to / don't have time to work on osu! projects anymore. Seeing as the Lazer API is entirely different from the current one, I suggest you create another library (I would be very glad to accept your PRs, unfortunately having two different API versions supported in the same library doesn't really appeal to me, and rewriting the library to support the latest version is not ideal, mostly due to people not using proper vendoring).
